/**
 * Terraform outputs for Bedrock Agent deployment
 */

##############################################################################
# Agent Information
##############################################################################

output "agent_id" {
  description = "The ID of the Bedrock Agent (use this for BEDROCK_AGENT_ID)"
  value       = aws_bedrockagent_agent.main.agent_id
}

output "agent_arn" {
  description = "The ARN of the Bedrock Agent"
  value       = aws_bedrockagent_agent.main.agent_arn
}

output "agent_name" {
  description = "The name of the Bedrock Agent"
  value       = aws_bedrockagent_agent.main.agent_name
}

output "agent_status" {
  description = "The status of the Bedrock Agent"
  value       = aws_bedrockagent_agent.main.agent_status
}

##############################################################################
# Agent Alias Information
##############################################################################

output "agent_alias_id" {
  description = "The ID of the Bedrock Agent Alias (use this for BEDROCK_AGENT_ALIAS_ID)"
  value       = aws_bedrockagent_agent_alias.main.agent_alias_id
}

output "agent_alias_arn" {
  description = "The ARN of the Bedrock Agent Alias"
  value       = aws_bedrockagent_agent_alias.main.agent_alias_arn
}

output "agent_alias_name" {
  description = "The name of the Bedrock Agent Alias"
  value       = aws_bedrockagent_agent_alias.main.agent_alias_name
}

##############################################################################
# IAM Role Information
##############################################################################

output "agent_role_arn" {
  description = "The ARN of the IAM role used by the Bedrock Agent"
  value       = aws_iam_role.bedrock_agent.arn
}

output "agent_role_name" {
  description = "The name of the IAM role used by the Bedrock Agent"
  value       = aws_iam_role.bedrock_agent.name
}

##############################################################################
# CloudWatch Logs
##############################################################################

output "log_group_name" {
  description = "The name of the CloudWatch Log Group for agent logs"
  value       = aws_cloudwatch_log_group.bedrock_agent.name
}

output "log_group_arn" {
  description = "The ARN of the CloudWatch Log Group"
  value       = aws_cloudwatch_log_group.bedrock_agent.arn
}

##############################################################################
# Model Information
##############################################################################

output "foundation_model_id" {
  description = "The foundation model ID used by the agent"
  value       = var.foundation_model_id
}

output "foundation_model_arn" {
  description = "The ARN of the foundation model"
  value       = data.aws_bedrock_foundation_model.agent_model.model_arn
}

##############################################################################
# Environment Configuration for TypeScript Application
##############################################################################

output "env_file_content" {
  description = "Content for .env file (copy this to your .env file)"
  value = <<-EOT
    # AWS Bedrock Agent Configuration
    # Generated by Terraform on ${timestamp()}

    BEDROCK_AGENT_ID=${aws_bedrockagent_agent.main.agent_id}
    BEDROCK_AGENT_ALIAS_ID=${aws_bedrockagent_agent_alias.main.agent_alias_id}
    AWS_REGION=${var.aws_region}

    # Optional: Enable trace logging
    # ENABLE_TRACE=true
  EOT
}

##############################################################################
# Quick Start Commands
##############################################################################

output "quick_start_commands" {
  description = "Quick start commands for testing the agent"
  value = <<-EOT

    ═══════════════════════════════════════════════════════════
    Bedrock Agent Deployed Successfully!
    ═══════════════════════════════════════════════════════════

    Agent Details:
    - Agent ID:       ${aws_bedrockagent_agent.main.agent_id}
    - Alias ID:       ${aws_bedrockagent_agent_alias.main.agent_alias_id}
    - Region:         ${var.aws_region}
    - Model:          ${var.foundation_model_id}
    - Environment:    ${var.environment}

    Next Steps:

    1. Update your .env file:

       echo 'BEDROCK_AGENT_ID=${aws_bedrockagent_agent.main.agent_id}' >> .env
       echo 'BEDROCK_AGENT_ALIAS_ID=${aws_bedrockagent_agent_alias.main.agent_alias_id}' >> .env
       echo 'AWS_REGION=${var.aws_region}' >> .env

    2. Test your agent:

       npm test

    3. Start interactive chat:

       npm run chat

    4. View CloudWatch logs:

       aws logs tail ${aws_cloudwatch_log_group.bedrock_agent.name} --follow

    ═══════════════════════════════════════════════════════════
  EOT
}

##############################################################################
# AWS Console Links
##############################################################################

output "console_links" {
  description = "AWS Console links for managing the agent"
  value = {
    agent = "https://console.aws.amazon.com/bedrock/home?region=${var.aws_region}#/agents/${aws_bedrockagent_agent.main.agent_id}"
    logs  = "https://console.aws.amazon.com/cloudwatch/home?region=${var.aws_region}#logsV2:log-groups/log-group/${replace(aws_cloudwatch_log_group.bedrock_agent.name, "/", "$252F")}"
    iam   = "https://console.aws.amazon.com/iam/home#/roles/${aws_iam_role.bedrock_agent.name}"
  }
}
